### ISSUE TITLE
[Feature request] List previously passing testcases

### ISSUE THREAD

**Issue by harsilspatel** [allure-framework/allure2#876] opened 2019-01-10 05:03 UTC
#### I'm submitting a ... 
  - [x] feature request

I believe it would be really helpful if there was another section that would list the testcases that passed previous tests but fail in latest test. For instance, I have ~900 testcases, and in a previous test the number of testcases passed was 564, however, that number decremented by one in the latest test. My code changes did fix a bug for some of the test cases, but clearly, some a greater number of testcases didn't pass.

**Comment by baev** [comment] 2019-01-14 16:12
> Correct me if I'm wrong but I don't think it's ported there.

This feature is adaptor independent

Duplicate of #858

**Closed by baev** 2019-01-14 16:12 UTC
