### ISSUE TITLE
Export Allure Report to a single HTML File

### ISSUE THREAD

**Issue by jakerolandaban** [allure-framework/allure2#755] opened 2018-02-21 20:21 UTC
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Allure Report is only available as long as i have the json files to generate it and keep the terminal open.

#### What is the motivation / use case for changing the behavior?
Need a single HTML file to keep track of for historical information of the report, and can be send as 1 file to the whole team. (e.g February2018_Report.html)

I tried saving the report as Webpage, Complete but the webpage was empty, have loading icons, and 404 not found.

#### Please tell us about your environment:
I'm using allure 2.5.0 and allure-behave
using allure serve {folder} in the terminal to generate the report

And that's all i believe what i am doing

**Comment by khdevnet** [comment] 2018-04-02 08:28
It's a good idea and we can send this report in email to customers.

**Comment by twixdouble** [comment] 2018-04-02 08:30
it's really a must-have feature - please do it as soon as possible

**Comment by omitiev** [comment] 2018-04-02 08:38
Agree. I would like to have a saved version of previous reports for using when it's needed.

**Comment by jakerolandaban** [comment] 2018-04-02 15:21
I actually found a workaround for this, you can use `allure generate` command to save the website files into a specific folder (files include .json files and index.html).

Once you do that you can store all of it on an aws s3 bucket and enable web hosting. This way you can just send the Link of the report allure has generated.

**Comment by marcel9414** [comment] 2018-05-14 10:38
Hello!
This request has been implemented? I need the same, an html with all the steps to send it to the client. 

Thanks!

**Comment by Sup3rGeo** [comment] 2018-05-21 15:20
@baev is the single html report already available?

Apparently this was implemented in https://github.com/allure-framework/allure2/issues/127?
Also might be duplicate of  https://github.com/jenkinsci/allure-plugin/issues/21.

It seems to be implemented in this java file:
https://github.com/allure-framework/allure2/blob/master/allure-generator/src/main/java/io/qameta/allure/core/ReportWebPlugin.java

**Comment by SymphonicJohn** [comment] 2018-08-20 15:04
@jakerolandaban I was able to serve a _**single**_ report by placing it in an s3 bucket as you described.
Thanks for that.
Can you link to or elaborate on how this would work with multiple test runs?
When I go to the buckets suggested domain: bucket-name.s3-website-us-west-2.amazonaws.com
the path /# is added by default and the 'trend' section is blank.
Thanks

**Comment by jakerolandaban** [comment] 2018-08-20 16:42
@SymphonicJohn you're running multiple test runs but only 1 is being shown? did I get that correct?
for the trends, try to look up categories.json on allure framework docs

**Comment by Sup3rGeo** [comment] 2018-09-11 18:37
You can use the command `allure generate <alluredir>` to create html files. This folder you could send around, but you can only directly open the `index.html` file with Edge or Firefox.

For Chrome, you need the `--allow-file-access-from-files` flag when running chrome, according to this:
https://stackoverflow.com/questions/18586921/how-to-launch-html-using-chrome-at-allow-file-access-from-files-mode.
Also it gives you other options, like running `python -m http.server` in the results folder so you don't have to use that option.

**Comment by amarusic** [comment] 2018-10-30 10:21
Is any news about generation Allure Report as single HTML File without dependency to json and csv files?

**Comment by goodbomb** [comment] 2018-10-30 20:37
+1

**Comment by jmatthews79** [comment] 2018-11-14 20:47
> I actually found a workaround for this, you can use `allure generate` command to save the website files into a specific folder (files include .json files and index.html).
> 
> Once you do that you can store all of it on an aws s3 bucket and enable web hosting. This way you can just send the Link of the report allure has generated.

How do you upload the folder to the S3 bucket? I dont want to have to do a put request per file in the folder? I dont think its possible to upload anything other than single files.

**Comment by rapidroamer** [comment] 2018-12-07 03:15
+1

**Comment by slavvka** [comment] 2019-01-07 23:15
+1

**Comment by aikrasnov** [comment] 2019-02-21 14:11
+1

**Comment by chunji08** [comment] 2019-02-22 19:56
+1 
If there is some update, can someone share ?  
I would like this report carries: 
1) the current execution statics, suc/failure/skilp rate, in such fancy allure style. 
2) maybe the past 10, 100 execution history, in a diagram chart. 
3) Provide a link, where if the user wants more details, they can click the link to go to the actual jenkins web page. 

Thanks a lot ! 
-cji

**Comment by rafaelcs** [comment] 2019-03-19 02:44
> I actually found a workaround for this, you can use `allure generate` command to save the website files into a specific folder (files include .json files and index.html).
> 
> Once you do that you can store all of it on an aws s3 bucket and enable web hosting. This way you can just send the Link of the report allure has generated.

@jakerolandaban I want to do just that, the problem is that after generating the results (`allure generate`) and trying to open only the HTML file, the result is not shown, only if I run the `allure open` command, but my idea is to generate the report and view it in my bucket. More tips?

**Comment by kool79** [comment] 2019-04-17 15:21
@rafaelcs 
did you read comment by @Sup3rGeo above?
> For Chrome, you need the --allow-file-access-from-files flag

**Comment by dreambe** [comment] 2019-04-22 12:01
> Is any news about generation Allure Report as single HTML File without dependency to json and csv files?
> 
> Thanks!

+1

**Comment by soduor** [comment] 2019-05-06 03:01
> > I actually found a workaround for this, you can use `allure generate` command to save the website files into a specific folder (files include .json files and index.html).
> > Once you do that you can store all of it on an aws s3 bucket and enable web hosting. This way you can just send the Link of the report allure has generated.
> 
> @jakerolandaban I want to do just that, the problem is that after generating the results (`allure generate`) and trying to open only the HTML file, the result is not shown, only if I run the `allure open` command, but my idea is to generate the report and view it in my bucket. More tips?


> I actually found a workaround for this, you can use `allure generate` command to save the website files into a specific folder (files include .json files and index.html).
> 
> Once you do that you can store all of it on an aws s3 bucket and enable web hosting. This way you can just send the Link of the report allure has generated.

Hi. Could you please elaborate on how you achieved this? I've stored my files in an s3 bucket but I'm getting a 404 error when visit the s3 endpoint. Any help will be greatly appreciated

**Comment by aaa-jake** [comment] 2019-05-09 17:05
> > > I actually found a workaround for this, you can use `allure generate` command to save the website files into a specific folder (files include .json files and index.html).
> > > Once you do that you can store all of it on an aws s3 bucket and enable web hosting. This way you can just send the Link of the report allure has generated.
> > 
> > 
> > @jakerolandaban I want to do just that, the problem is that after generating the results (`allure generate`) and trying to open only the HTML file, the result is not shown, only if I run the `allure open` command, but my idea is to generate the report and view it in my bucket. More tips?
> 
> > I actually found a workaround for this, you can use `allure generate` command to save the website files into a specific folder (files include .json files and index.html).
> > Once you do that you can store all of it on an aws s3 bucket and enable web hosting. This way you can just send the Link of the report allure has generated.
> 
> Hi. Could you please elaborate on how you achieved this? I've stored my files in an s3 bucket but I'm getting a 404 error when visit the s3 endpoint. Any help will be greatly appreciated

Have you enabled the web-hosting feature of your s3 bucket?

**Comment by ntindle** [comment] 2019-08-09 14:18
Love this idea and it would be fantastic

**Comment by rafaelcs** [comment] 2019-08-14 17:30
Here is my solution to upload the report to AWS S3

```
# Generate Allure report
allure generate -c reports/allure-results -o reports/allure-results-html

# Upload HTML report to AWS S3
aws s3 sync reports/allure-results-html s3://your_bucket/
```

**Comment by fescobar** [comment] 2019-08-14 19:31
I've added to Allure Docker container the emailable report feature. You can export it to a simple Html.
https://github.com/fescobar/allure-docker-service#customize-emailable-report

**Comment by eleni-salamani** [comment] 2020-01-03 12:49
+1

**Comment by DikshaBaluja** [comment] 2020-01-14 13:09
@Sup3rGeo Is it also possible if allure server is not up and running ? Thanks

**Comment by poovaraj** [comment] 2020-02-15 04:35
> ReportWebPlugin

How to generate static report using ReportWebPlugin ?

**Comment by abhi8130** [comment] 2020-05-29 19:17
How could we access the allure reports .html file in Github? Locally we can achieve it by using allure serve allure-results / allure generate but in Github how we can achieve it

**Comment by umeshwalagedara** [comment] 2020-07-14 12:03
This  allure generate thing does not work for me...     The data are not appearing in the report....    Pages are there but values are not coming...  is there any thing extra we have to do.

**Comment by jmatthews79** [comment] 2020-07-14 13:56
@umeshwalagedara Can you tell us what steps you have tried so far? How did you install allure?

**Comment by fescobar** [comment] 2020-07-14 14:19
> This allure generate thing does not work for me... The data are not appearing in the report.... Pages are there but values are not coming... is there any thing extra we have to do.

@umeshwalagedara you have here multiple examples: https://github.com/fescobar/allure-docker-service#generate-allure-results
Skip the docker part.

**Comment by karthick4kumaran** [comment] 2020-09-22 14:17
Guys, I posted a workaround with just a few lines of shell script for mac and batch script for windows. Please find my answer in the following link,
https://stackoverflow.com/questions/41960081/how-to-send-an-email-of-allure-report/64011632#64011632

We just need to share the entire allure-report folder over the email and the user who downloads it can open the allure report with the shell script/batch script. They don't need to have allure installed in their system as well. Check it out. It's free and it doesn't involve any third party or costly amazon was bucket.

**Comment by lalithach** [comment] 2020-11-09 11:11
Just like <allureurl>/graph that displays the trend seperately, is there are any way to view the status of the tests passed and failed   ??? so that, that snapshot can be shared in the email.

**Comment by rakeshnambiar** [comment] 2021-02-02 10:01
Hello all, Is there any way to generate the summary report for each test execition on the `allure sever` something like https://qameta.io/ ?

**Comment by danishs81** [comment] 2021-03-25 16:32
> Here is my solution to upload the report to AWS S3
> 
> ```
> # Generate Allure report
> allure generate -c reports/allure-results -o reports/allure-results-html
> 
> # Upload HTML report to AWS S3
> aws s3 sync reports/allure-results-html s3://your_bucket/
> ```

I tried it all (manually uploaded the folder to my bucket) but when I access the https://mybucket/index.html the page is served however, with the infamous NaN% on the main page and no other data getting populated.

**Comment by MihanEntalpo** [comment] 2021-12-16 13:50
I've made a tool for my own usage, that is compiling output folder of `allure generate` into a single html file that is working fine.
It's alpha version, where are not pip module yet, but it's already working: https://github.com/MihanEntalpo/allure-single-html-file

**Comment by ealfaroorange** [comment] 2022-03-29 14:35
+1

**Comment by Khouloud-moalla** [comment] 2022-05-16 09:40
> it in my bucket
can you explain more !

**Comment by MihanEntalpo** [comment] 2022-05-16 09:56
@Khouloud-moalla 
> > it in my bucket
> > can you explain more !

If your question is about single-file allure builder, you can view readme at https://github.com/MihanEntalpo/allure-single-html-file#readme

**Comment by Khouloud-moalla** [comment] 2022-05-26 14:30
> @Khouloud-moalla
> 
> > > it in my bucket
> > > can you explain more !
> 
> If your question is about single-file allure builder, you can view readme at https://github.com/MihanEntalpo/allure-single-html-file#readme

if I combine them how I can know which file for which browser!!

**Comment by MihanEntalpo** [comment] 2022-05-26 15:26
> > @Khouloud-moalla
> > > > it in my bucket
> > > > can you explain more !
> > 
> > 
> > If your question is about single-file allure builder, you can view readme at https://github.com/MihanEntalpo/allure-single-html-file#readme
> 
> if I combine them how I can know which file for which browser!!

It's easy. Just use firefox or any chrome-based browser on generated file "complete.html" :)

**Comment by jabhijeet** [comment] 2022-06-22 03:22
> @Khouloud-moalla
> 
> > > it in my bucket
> > > can you explain more !
> 
> If your question is about single-file allure builder, you can view readme at https://github.com/MihanEntalpo/allure-single-html-file#readme

Can you please release/publish a version for allure-combine?

Thanks

**Comment by MihanEntalpo** [comment] 2022-06-22 03:31
> Can you please release/publish a version for allure-combine?

@jabhijeet already done. Working version 1.0.6 in PIP 

Also, discussion about allure-combine is offtopic here, so, you are welcome in Issues page of allure-combine project if you have any troubles

**Comment by OrenBerreby** [comment] 2022-07-06 08:56
@MihanEntalpo

Hey I seem to have an issue running this, I have python 3.9 installed but whenever i run the allure combine command I get
"Could not parse arguments: Expected a command, got combine"
Do you know how I might resolve this? Really want to get this working, I am definitely in the right directory of the allure results tried also the report.

Thank you

**Comment by MihanEntalpo** [comment] 2022-07-06 12:50
@OrenBerreby would you kindly create an issue in the repository of allure-combine?

**Comment by erineia** [comment] 2022-08-19 19:20
Pessoal, alguém pode me ajudar com uma questão.
Tenho umas classes que ao clicar abre uma guia com o PDF, é uma guia referente a uns testes que precisa gerar o PDF, porém não sei como apresentar eles no relatório allure noTest body, será que alguém conseguem me ajudar com isso, qual anotação, que jeito eu faria isso?

![image](https://user-images.githubusercontent.com/51462490/185690559-7489c235-af5b-4908-9aae-65e96e910dff.png)

**Comment by fescobar** [comment] 2022-08-21 10:37
> Pessoal, alguém pode me ajudar com uma questão. Tenho umas classes que ao clicar abre uma guia com o PDF, é uma guia referente a uns testes que precisa gerar o PDF, porém não sei como apresentar eles no relatório allure noTest body, será que alguém conseguem me ajudar com isso, qual anotação, que jeito eu faria isso?
> 
> ![image](https://user-images.githubusercontent.com/51462490/185690559-7489c235-af5b-4908-9aae-65e96e910dff.png)

Write in eglish man

**Comment by erineia** [comment] 2022-08-22 13:34
Greetings colleagues, can someone please help me?
I have some classes that open a tab with a PDF file, but I don't know how to present these PDFs in the allure report inside Test body, can anyone help me with this, what annotations, which way would I do this?
![image](https://user-images.githubusercontent.com/51462490/185933859-b97a7365-9e8b-4a7b-a9a7-bf4c7712f62c.png)

**Comment by ReachHeaven** [comment] 2023-08-24 07:53
+1

**Closed** 2023-08-24 15:02 UTC

**Comment by rnagarajaiah** [comment] 2024-06-18 05:21
@Khouloud-moalla , I tried generating the html file, it generates with dependencies. The html report is not loading the data, I tried in different browser, same issue is being observed.
