### ISSUE TITLE
Allure for Jira plugin api mismatch with Allure Jira Plugin api

### ISSUE THREAD

**Issue by SeleniumTestAB** [allure-framework/allure2#999] opened 2019-09-02 18:33 UTC
**Describe the bug**
Allure for Jira plugin in version 1.5 had refactoring, which was not done on Jira Plugin. This generates errors and exceptions when trying to use newest plugin version for integration purposes

**To Reproduce**
1. Install newest version of Allure for Jira Plugin
2. Use CLI server (for example Jenkins) with Allure Plugin installed
3. Configure CLI Plugin to use newest Allure version (2.12.1 at time of writing this issue)
4. Configure Job to inject proper Env Variables
5. Run tests and wait for them to finish

**Expected behavior**
The exception rises. The "id" attribute is unknown to api thus failing job.

**Screenshots**

**Environment (please complete the following information):**

| Allure version | 2.12.1 |
| Allure for Jira | 1.5 |

**Additional context**
Sadly we can not downgrade our Plugin version because the older one is not compatibile with our Jira. Also i though of making pull request with fix, but i might not be able to refactor TestCase results.

**Comment by SeleniumTestAB** [comment] 2019-09-07 13:22
@eroshenko can you take a look?

**Comment by Baiskey** [comment] 2020-01-31 11:58
Hi guys,

can you look at that issue? This functionality is quite important for me. I've tried sending Allure report on different versions in Allure for Jira and Allure (for tests) but finally I wasn't able to do it. I'm attaching exceptions, which I got during my trials:

io.qameta.allure.jira.retrofit.ServiceException: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>500</status-code><message>bundle [io.qameta.allure.jira]</message><stack-trace>com.atlassian.activeobjects.internal.ActiveObjectsInitException: bundle [io.qameta.allure.jira]
   at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects$1$1$1.call(TenantAwareActiveObjects.java:95)
   at com.atlassian.activeobjects.osgi.TenantAwareActiveObjects$1$1$1.call(TenantAwareActiveObjects.java:86)
   at com.atlassian.sal.core.executor.ThreadLocalDelegateCallable.call(ThreadLocalDelegateCallable.java:38)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   at java.lang.Thread.run(Thread.java:748)
Caused by: com.atlassian.activeobjects.internal.ActiveObjectsSqlException: There was a SQL exception thrown by the Active Objects library:
Database:
   - name:PostgreSQL
   - version:9.4.23
   - minor version:4
   - major version:9
Driver:
   - name:PostgreSQL Native Driver
   - version:PostgreSQL 9.4.1212

org.postgresql.util.PSQLException: ERROR: relation "AO_96A441_TEST_RESULT" does not exist



io.qameta.allure.jira.retrofit.ServiceException: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>500</status-code><message>Unrecognized field "issueKeys" (Class io.qameta.allure.jira.launch.dto.LaunchDto), not marked as ignorable
 at [Source: org.apache.catalina.connector.CoyoteInputStream@41353c8c; line: 1, column: 22] (through reference chain: io.qameta.allure.jira.launch.dto.LaunchDto["issueKeys"])</message><stack-trace>org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecogn
ized field "issueKeys" (Class io.qameta.allure.jira.launch.dto.LaunchDto), not marked as ignorable 



io.qameta.allure.jira.retrofit.ServiceException: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>500</status-code><message>Unrecognized field "id" (Class io.qameta.allure.jira.rest.dto.LaunchExport), not marked as ignorable

**Comment by baev** [comment] 2020-01-31 13:02
@Baiskey you are using Jira plugin for Allure Enterprise, not for Allure Report

**Comment by Baiskey** [comment] 2020-02-02 13:10
@baev I have Jira Plugin for Allure from this location https://marketplace.atlassian.com/apps/1219604/allure-for-jira?hosting=server&tab=overview and I am using instructions from this document https://github.com/allure-framework/allure2/tree/master/plugins/jira-plugin#allure-jira-plugin 

To upload Allure Report to my Jira server instance, I'm using this instruction https://docs.qameta.io/allure/#_report_generation

Unfortunately I can't do this due to above issues.

As for me, I am using proper Jira Plugin for Allure - can you provide proper plugin for uploading Allure report to Jira?

**Comment by kamwar** [comment] 2020-02-05 17:20
Hi guys,

I have a similar issue as @Baiskey
```
io.qameta.allure.jira.retrofit.ServiceException: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>500</status-code><message>Unrecognized field "id" (Class io.qameta.allure.jira.rest.dto.LaunchExport), not marked as ignorable
 at [Source: org.apache.catalina.connector.CoyoteInputStream@4ea20d7b; line: 1, column: 8] (through reference chain: io.qameta.allure.jira.rest.dto.LaunchExport["id"])</message><stack-trace>org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "id" (Class io.qameta.allure.jira.rest.dto.LaunchExport), not marked as ignorable
 at [Source: org.apache.catalina.connector.CoyoteInputStream@4ea20d7b; line: 1, column: 8] (through reference chain: io.qameta.allure.jira.rest.dto.LaunchExport["id"])
	at org.codehaus.jackson.map.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:53)
```
| Allure version | 2.13.1
| Allure for Jira | 1.5 |

Do you have any clue what causes this problem?

**Comment by DmitriyRocks** [comment] 2020-02-10 10:05
Experiencing similar problem with Allure for Jira plugin 1.5.0:

io.qameta.allure.jira.retrofit.ServiceException: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>500</status-code><message>Unrecognized field "id" (Class io.qameta.allure.jira.rest.dto.LaunchExport), not marked as ignorable
 at [Source: org.apache.catalina.connector.CoyoteInputStream@7a226813; line: 1, column: 8] (through reference chain: io.qameta.allure.jira.rest.dto.LaunchExport["id"])</message><stack-trace>org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "id" (Class io.qameta.allure.jira.rest.dto.LaunchExport), not marked as ignorable

Allure 2.10
Jira server 8.5.0

**Closed** 2020-04-21 08:57 UTC
Labels: type:bug
