### ISSUE TITLE
History of test limited to 5

### ISSUE THREAD

**Issue by tedrigofra** [allure-framework/allure2#906] opened 2019-03-06 15:22 UTC
In the Allure report there are the tabs Overview, History and Retries.
When I click on History then I see only 5 previous test results, although Jenkins has many more builds with Allure reports.
Why is it only displaying 5 previous test results in the History tab? How can I see more in the History tab? Do I have to configure that somewhere?
I use the latest Allure versions and JUnit 5.4 and Maven and JDK 11.

**Comment by baev** [comment] 2019-03-07 09:42
Duplicate of #347

**Closed by baev** 2019-03-07 09:42 UTC
Labels: type:invalid
