### ISSUE TITLE
Dynamical environment properties

### ISSUE THREAD

**Issue by tedrigofra** [allure-framework/allure2#907] opened 2019-03-06 15:27 UTC
The environment.properties file is a very static way of defining.
I would like to gather automatically the information for the environment to be displayed in the Allure report while the test is running and not maintain a environment.properties file manually. Is that possible?

**Comment by baev** [comment] 2019-03-07 09:41
Not yet at the moment. We have a concept of new environments feature, that would be shipped in future allure releases. You can track the issue #130 

Duplicate of #130

**Closed by baev** 2019-03-07 09:41 UTC
Labels: type:invalid
