### ISSUE TITLE
Unknown Hook is existed in report

### ISSUE THREAD

**Issue by ledaivuong** [allure-framework/allure2#1030] opened 2019-12-01 17:02 UTC
In my report, it exists an Unknown Hook which I'm not sure what it is and how can skip it
![2019-12-02_00h01_20](https://user-images.githubusercontent.com/22213252/69917304-fff33400-1496-11ea-8bf1-9faa996ecd3a.png)

**Comment by baev** [comment] 2019-12-01 18:56
duplicate of https://github.com/webdriverio-boneyard/wdio-allure-reporter/issues/164

**Closed by baev** 2019-12-01 18:56 UTC
Labels: type:bug
