### ISSUE TITLE
DisplayName is not shown in the report for tests with @ParameterizedTest annotation in Juni5

### ISSUE THREAD

**Issue by BandyaDhapate** [allure-framework/allure2#951] opened 2019-05-28 20:38 UTC
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
Correct @DisplayName text is not captured in the report for the test methods annotated  with @ParameterizedTest instead text from @ValueSource/@CsvSource  is displayed as test's display name in the report.. 
@DisplayName text shows up for tests with @Test annotation. If same class has methods with @Test and @ParametrizedTest then correct DisplayName text only shows for @Test methods and not for @ParameterizedTest methods. 

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Create a class with 2 test methods one annotated with @Test and another with @ParameterizedTest. 
2. Write @DisplayName for both tests. 
3. Execute Test gradle task
4. Check the report 

#### What is the expected behavior?
@DisplayName text shall appear for all active test method annotations supported by Junit5. 
E.g. @Test,@ParameterizedTest, @RepeatedTest

#### What is the motivation / use case for changing the behavior?
Improve readability of the test report when tests are annotated other than @Test

#### Please tell us about your environment:
Selenium, Junit5, Gradle, Java

| Allure version | 2.7.0 |
| --- | --- |
| Test framework | JUnit5 |
| Allure integration | allure-junit5@2.11.0 |
| Generate report using | allure-gradle@2.5 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment] 2019-09-09 13:29
Duplicate of https://github.com/allure-framework/allure-java/issues/363

**Closed by baev** 2019-09-09 13:29 UTC
Labels: type:bug
