### ISSUE TITLE
Error from azure plugin: Failed to publish test run data: System.ArgumentException: Unknown test runner

### ISSUE THREAD

**Issue by grazielegrc** [allure-framework/allure2#1963] opened 2023-03-31 17:14 UTC
**Describe the bug**
I am trying to generate allure report from azureDevos pipeline using the allure plugin but I am getting this error:

##[warning]Failed to publish test run data: System.ArgumentException: Unknown test runner
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestDataPublisher.ParseTestResultsFile(TestRunContext runContext, List`1 testResultFiles) in D:\a\1\s\src\Agent.Worker\TestResults\TestDataPublisher.cs:line 124
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestDataPublisher.PublishAsync(TestRunContext runContext, List`1 testResultFiles, PublishOptions publishOptions, CancellationToken cancellationToken) in D:\a\1\s\src\Agent.Worker\TestResults\TestDataPublisher.cs:line 66

When I inspect the browser network with Allure report tab opened in AzureDevOps,  I see the following error:

Request URL: https://extmgmt.dev.azure.com/CostaIT/_apis/ExtensionManagement/InstalledExtensions/ivang7/allure-test-reports/Data/Scopes/Default/Current/Collections/%24settings/Documents/baseUrl
Request Method: GET
Status Code: 404 

Response:
{"$id":"1","innerException":null,"message":"%error=\"1660002\";%:The collection does not exist\r\n%error=\"1660002\";%:The collection does not exist","typeName":"Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.DocumentCollectionDoesNotExistException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi","typeKey":"DocumentCollectionDoesNotExistException","errorCode":0,"eventId":3000}

**To Reproduce**
1. Go to 'azureDevOps' pipeline;
2. Add a task: generate allure report
3. Run pipeline
4. After pipeline finishes, go to Allure report tab

**Expected behavior**
Allure report is properly displayed.

**Screenshots**

**Environment (please complete the following information):**

| Allure version | 1.3.0 |
| --- | --- |
| Test framework | NUnit - 3.13.3 |
| Generate report using | allure-report-plugin |

**Additional context**

**Comment by baev** [comment] 2024-01-10 16:50
Duplicate of #1140

**Closed by baev** 2024-01-10 16:50 UTC
Labels: type:bug

**Comment by baev** [comment] 2024-02-01 12:46
Official Allure extension for Azure Pipelines are now available https://marketplace.visualstudio.com/items?itemName=qameta.allure-azure-pipelines

History isn't yet supported, but we'll get there! Please submit feedback to our [discussions](https://github.com/orgs/allure-framework/discussions)
