### ISSUE TITLE
There is no log output in allure

### ISSUE THREAD

**Issue by nullpointer00** [allure-framework/allure2#1656] opened 2022-05-17 13:51 UTC
**Describe the bug**
Hi I was using Allure and found that the log message was not collected

**To Reproduce**
def test_method(logger)
   logger.info("hi") #Use fixtures to generate a logger
if __name__ == '__main__':
   pytest.main(["-s", "--alluredir={}".format(DirInfo.report_dir.value),#Please replace the path
                 "test_cases.py"])
    result = os.system(r"allure serve {}".format(DirInfo.report_dir.value))
    print("result={}".format(result))
   
**Expected behavior**
I would like to see logs in the report

**Screenshots**
![image](https://user-images.githubusercontent.com/31955536/168825575-ef46f5fe-0d20-4326-be6c-9f641868984a.png)

**Environment (please complete the following information):**

| Allure version | 2.18.0 |
| --- | --- |
| Test framework | pytest@7.1.2 |
| Allure adaptor | allure-pytest@2.9.45 |
| Generate report using | allure-python-commons@2.9.45 |

**Comment by delatrie** [comment] 2023-01-19 09:35
Duplicate of allure-framework/allure-python#663

**Closed by delatrie** 2023-01-19 09:35 UTC
Labels: type:bug
