### ISSUE TITLE
JunitXmlPlugin ignores std-out

### ISSUE THREAD

**Issue by akranga** [allure-framework/allure2#790] opened 2018-05-11 06:50 UTC
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request

#### What is the current behavior?
Many of the testing tools put important information in std-out section of their test reports. Currently `JunitXmlPlugin` ignores this section (`xml:testsuites.testsuite.testcase.system-out`)

#### What is the expected behavior?
As a user I want to be able to access std-out information in the generated html report. 

#### What is the motivation / use case for changing the behavior?
As a user I want to use allure to browse my test cases which were not written originally in Java, however test reports were exported in JUnit xml format and then parsed by allure. I want to see important information that left in std-out of the test case.

#### Please tell us about your environment:

| Allure version | 2.6.0 |

**Comment by akranga** [comment] 2018-05-11 06:51
Should be happy to contribute. However will require some directions. The code of Allure is unfamiliar to me yet

**Comment by aptester** [comment] 2018-05-27 05:04
#676 and #744 refer the same issue.

**Comment by baev** [comment] 2019-01-14 14:00
Duplicate of #744

**Closed by baev** 2019-01-14 14:00 UTC
