### ISSUE TITLE
open pr serve is error！

### ISSUE THREAD

**Issue by yanghuizhi** [allure-framework/allure2#2265] opened 2023-12-22 07:33 UTC
### Describe the Bug

在使用 allure.bat serve  xxx 和 allure.bat open xxx 时，都会自动启动浏览器，设置APS之后，每次都会弹出浏览器，我不需要每次都弹出，只需要启动站点即可，但是没有这样的服务。

 2023-12-22 15:24:13 | INFO | allure.bat 版本为: 2.17.2
 2023-12-22 15:24:13 | INFO | python     版本为: Python 3.9.0

### Steps to Reproduce

1

### Expected Behaviour

Server started at <http://10.111.111.11:115/>. Press <Ctrl+C> to exit

只启动类似这样服务，否则，请不要弹出浏览器。

### What Language are you using?

Python

### What Framework/Allure Integration you are using?

allure

### What version of Allure Integration you are using?

2.17.2

### What version of Allure Report you are using?

2.17.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment] 2024-01-08 14:46
Duplicate of #1175

**Closed by baev** 2024-01-08 14:46 UTC
Labels: type:bug, triage
