### ISSUE TITLE
Allure report fails to generate after 60 seconds

### ISSUE THREAD

**Issue by santhoshvinayaka** [allure-framework/allure2#1692] opened 2022-06-30 08:21 UTC
**Describe the bug**
I am running around 1500 test cases on Bamboo and I am using allure report. It works fine when the test cases is around 1000, but fails to generate the report if it crosses more than 1000. The allure timeout is 60 secs. It fails to generate after this time.

**To Reproduce**
1. Have a set of test cases which numbers to more than 1200 and execute them on Bamboo.
2. Check the allure report after the execution is complete.

**Expected behavior**
A clear report with pass, fail, and broken test cases should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/62627577/176628386-88d4b96c-b071-4c8e-b283-4f29a14629f7.png)

**Environment (please complete the following information):**

| Allure version | 2.16.1 |
| --- | --- |
| Test framework | BDD Cucumber |

**POM.xml**
<dependencies>
    
    <dependency>
      <artifactId>xercesImpl</artifactId>
      <groupId>xerces</groupId>
      <version>2.11.0</version>
    </dependency>
    <dependency>
      <artifactId>guava</artifactId>
      <groupId>com.google.guava</groupId>
      <version>LATEST</version>
    </dependency>
    <dependency>
      <artifactId>cucumber-java8</artifactId>
      <groupId>io.cucumber</groupId>
      <scope>test</scope>
      <version>${cucumber.version}</version>
    </dependency>
    <dependency>
      <artifactId>lombok</artifactId>
      <groupId>org.projectlombok</groupId>
      <scope>provided</scope>
      <version>${lombok.version}</version>
    </dependency>
    <dependency>
      <artifactId>rest-assured</artifactId>
      <groupId>io.rest-assured</groupId>
      <version>${restAssured.version}</version>
    </dependency>
    <dependency>
      <artifactId>assertj-core</artifactId>
      <groupId>org.assertj</groupId>
      <version>3.9.1</version>
    </dependency>
    <dependency>
      <artifactId>cucumber-junit</artifactId>
      <groupId>io.cucumber</groupId>
      <version>${cucumber.version}</version>
      
    </dependency>
    <dependency>
      <artifactId>junit</artifactId>
      <groupId>junit</groupId>
      <version>4.12</version>
    </dependency>
    
    <dependency>
      <artifactId>commons-collections4</artifactId>
      <groupId>org.apache.commons</groupId>
      <version>4.1</version>
    </dependency>
    
    <dependency>
      <artifactId>commons-dbutils</artifactId>
      <groupId>commons-dbutils</groupId>
      <version>1.7</version>
    </dependency>
    <dependency>
      <artifactId>guice</artifactId>
      <exclusions>
        <exclusion>
          <artifactId>guava</artifactId>
          <groupId>com.google.guava</groupId>
        </exclusion>
      </exclusions>
      <groupId>com.google.inject</groupId>
      <scope>test</scope>
      <version>4.0</version>
    </dependency>
    <dependency>
      <artifactId>ojdbc7</artifactId>
      <groupId>com.oracle.weblogic</groupId>
      <version>12.1.3-0-0</version>
    </dependency>
    <dependency>
      <artifactId>sdoapi</artifactId>
      <groupId>com.oracle</groupId>
      <version>12.1.0.2.0</version>
    </dependency>
    <dependency>
      <artifactId>com.springsource.oracle.xdb</artifactId>
      <groupId>com.oracle.xdb</groupId>
      <version>10.2.0.2</version>
    </dependency>
    <dependency>
      <artifactId>mybatis</artifactId>
      <groupId>org.mybatis</groupId>
      <version>3.4.2</version>
    </dependency>
    <dependency>
      <artifactId>mybatis-dynamic-sql</artifactId>
      <groupId>org.mybatis.dynamic-sql</groupId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <artifactId>log4j-core</artifactId>
      <groupId>org.apache.logging.log4j</groupId>
      <version>${log4j.version}</version>
    </dependency>
    <dependency>
      <artifactId>log4j-api</artifactId>
      <groupId>org.apache.logging.log4j</groupId>
      <version>${log4j.version}</version>
    </dependency>
    <dependency>
      <artifactId>log4j-slf4j-impl</artifactId>
      <groupId>org.apache.logging.log4j</groupId>
      <version>${log4j.version}</version>
    </dependency>
    <dependency>
      <artifactId>slf4j-api</artifactId>
      <groupId>org.slf4j</groupId>
      <version>1.7.22</version>
    </dependency>
    <dependency>
      <artifactId>commons-logging</artifactId>
      <groupId>commons-logging</groupId>
      <version>1.2</version>
    </dependency>
    <dependency>
      <artifactId>jira-rest-java-client-api</artifactId>
      <exclusions>
        <exclusion>
          <artifactId>guava</artifactId>
          <groupId>com.google.guava</groupId>
        </exclusion>
      </exclusions>
      <groupId>com.atlassian.jira</groupId>
      <version>LATEST</version>
    </dependency>
    <dependency>
      <artifactId>jira-rest-java-client-core</artifactId>
      <exclusions>
        <exclusion>
          <artifactId>guava</artifactId>
          <groupId>com.google.guava</groupId>
        </exclusion>
      </exclusions>
      <groupId>com.atlassian.jira</groupId>
      <version>LATEST</version>
    </dependency>
    <dependency>
      <artifactId>fugue</artifactId>
      <exclusions>
        <exclusion>
          <artifactId>guava</artifactId>
          <groupId>com.google.guava</groupId>
        </exclusion>
      </exclusions>
      <groupId>io.atlassian.fugue</groupId>
      <version>4.7.2</version>
    </dependency>
    <dependency>
      <artifactId>mockito-core</artifactId>
      <groupId>org.mockito</groupId>
      <version>2.9.0</version>
    </dependency>
    <dependency>
      <artifactId>json</artifactId>
      <groupId>org.json</groupId>
      <version>20170516</version>
    </dependency>

    <dependency>
      <artifactId>cloning</artifactId>
      <groupId>uk.com.robust-it</groupId>
      <version>1.9.10</version>
    </dependency>
    
    <dependency>
      <artifactId>browsermob-core</artifactId>
      <groupId>net.lightbody.bmp</groupId>
      <version>2.1.5</version>
    </dependency>
    <dependency>
      <artifactId>cucumber-picocontainer</artifactId>
      <groupId>io.cucumber</groupId>
      <scope>test</scope>
      <version>${cucumber.version}</version>
    </dependency>
    <dependency>
      <artifactId>picocontainer</artifactId>
      <groupId>org.picocontainer</groupId>
      <scope>test</scope>
      <version>${picocontainer.version}</version>
    </dependency>
    
    <dependency>
      <artifactId>selenium-java</artifactId>
      <groupId>org.seleniumhq.selenium</groupId>
      <scope>test</scope>
      <version>${selenium.version}</version>
    </dependency>
    <dependency>
      <artifactId>selenium-server</artifactId>
      <groupId>org.seleniumhq.selenium</groupId>
      <scope>test</scope>
      <version>${selenium.version}</version>
    </dependency>
    <dependency>
      <artifactId>selenium-chrome-driver</artifactId>
      <groupId>org.seleniumhq.selenium</groupId>
      <scope>test</scope>
      <version>${selenium.version}</version>
    </dependency>
    <dependency>
      <artifactId>maven-compiler-plugin</artifactId>
      <groupId>org.apache.maven.plugins</groupId>
      <version>3.8.1</version>
    </dependency>
    <dependency>
      <artifactId>awt-color-factory</artifactId>
      <groupId>org.beryx</groupId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <artifactId>awaitility</artifactId>
      <groupId>org.awaitility</groupId>
      <version>3.0.0</version>
    </dependency>
    <dependency>
      <artifactId>commons-lang3</artifactId>
      <groupId>org.apache.commons</groupId>
      <version>3.9</version>
    </dependency>
    <dependency>
      <artifactId>allure-cucumber4-jvm</artifactId>
      <groupId>io.qameta.allure</groupId>
      <version>2.16.1</version>
    </dependency>
  </dependencies>
  <modelVersion>4.0.0</modelVersion>
  <properties>
    <allure.version>1.5.0</allure.version>
    <allureReportsDir>target/allure-results</allureReportsDir>
    <aspectj.version>1.8.10</aspectj.version>
    <cucumber.version>4.7.4</cucumber.version>
    <log4j.version>2.17.1</log4j.version>
    <lombok.version>1.18.10</lombok.version>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <picocontainer.version>2.15</picocontainer.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <resourcesFolder>resources</resourcesFolder>
    <restAssured.version>3.0.7</restAssured.version>
    <selenium.version>3.11.0</selenium.version>
  </properties>

**Comment by cheshi-mantu** [comment] 2022-06-30 08:23
hi, in your screenshot the error is caused by org.buildobject.process, not by allure binary, I would recommend starting with the build server settings relates to the timeouts.

**Comment by santhoshvinayaka** [comment] 2022-06-30 08:24
Also, I think if the timeout for the allure could be increased for more than 60 seconds, that would resolve the issue.

Thanks,
Santhosh

**Comment by santhoshvinayaka** [comment] 2022-06-30 10:12
Hi,

Could you please outline how and where that should be changed and we'll change it. This is a product invoked by Bamboo - all timeouts etc, are under control of the product we have chosen.

**Comment by baev** [comment] 2022-06-30 10:57
https://github.com/allure-framework/allure-bamboo/blob/54126bdbc3837b712708ca0ac8d52696184a850f/src/main/java/io/qameta/allure/bamboo/AllureCommandLineSupport.java#L17

**Comment by santhoshvinayaka** [comment] 2022-07-04 08:57
Hi baev,

We are using allure as 3rd party tool from bamboo. So, if you could please edit the source code and upload it in binary format, that would be really helpful.

Thanks,
Santhosh

**Comment by santhoshvinayaka** [comment] 2022-07-04 10:42
Hi @baev ,

I am not sure if that will work or not because we are using allure 2.16.1 as a third party. If you could also send instructions on what exactly to include, that'd be great as well.

Thanks,
Santhosh

**Comment by baev** [comment] 2022-07-04 15:20
@santhoshvinayaka there is no need to ping me so much. I made a PR https://github.com/allure-framework/allure-bamboo/pull/256 already, the reviewer is kinda busy right now, we expect that PR will be landed later this week

For urgent requests please consider using paying support option. Or you can try [Allure TestOps](https://qameta.io/) -- it has no such issue and build reports in real-time

**Comment by santhoshvinayaka** [comment] 2022-07-04 15:25
Thanks @baev 

Apologies for any inconvenience.

**Closed** 2022-07-04 17:44 UTC
Labels: type:bug

**Comment by baev** [comment] 2022-07-04 18:12
@santhoshvinayaka new version with the fixes is published to the market. Please update Allure Bamboo plugin to version 1.14.0

**Comment by santhoshvinayaka** [comment] 2022-07-05 07:56
@baev Thanks a lot.
