### ISSUE TITLE
Can't install Allure with Scoop

### ISSUE THREAD

**Issue by artburov** [allure-framework/allure2#1198] opened 2021-03-27 17:51 UTC
Can't install with scoop install allure

>PS> scoop install allure 
Installing 'allure' (2.13.8) [64bit]
The remote server returned an error: (403) Forbidden.
URL https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.zip is not valid

Same result trying download zip via browser, just Forbidden!

**Comment by alekslitvinenk** [comment] 2021-03-27 19:26
Same for Mac installation via Homebrew:
```shell
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "allure"
Download failed: https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.zip
```

**Comment by KimEklund13** [comment] 2021-03-28 00:41
I'm also running into issues while running `brew install allure` in my GitHub Actions script

```
=> Downloading https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.zip
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "allure"
Download failed: https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.zip
Error: Process completed with exit code 1.
```

However, if I run `brew uninstall allure && brew install allure` on my local machine (macOS 11.1) it downloads fine.

If I click on the [link for the zip file](https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.zip)  file I just see `Forbidden!`

**Comment by baev** [comment] 2021-03-28 14:23
yeah, we got rate-limited once again by Bintray

See #832 

BTW, both brew and scoop formulas were reverted from Maven Central to Bintray for some reason https://github.com/Homebrew/homebrew-core/pull/56549
https://github.com/ScoopInstaller/Main/pull/354

**Comment by baev** [comment] 2021-03-28 18:31
@KimEklund13 brew is fixed by now https://github.com/Homebrew/homebrew-core/pull/74058

**Comment by lewisob** [comment] 2021-03-28 23:54
Hi @baev any suggestions for a work around for Maven builds while bintray is rate-limited?

**Comment by KimEklund13** [comment] 2021-03-29 01:06
I can confirm that this works! Thank you @baev 
Just in case anyone else finds this thread with the same issue I had:

I had to use `macos-latest` system image for GitHub Actions which points to macOS 10.15. Using `macOS-11.0` (and updated version of brew) will cause a build failure because `macOS-11.0` [has been transited to private preview since January.](https://github.com/actions/virtual-environments/issues/2486)

To resolve this, continue to use `macos-latest` and add `brew update` to the GitHub Actions script to get this latest change for brew.

**Comment by baev** [comment] 2021-03-29 11:25
> Hi @baev any suggestions for a work around for Maven builds while bintray is rate-limited?

@lewisob What issues do you have with Maven builds? 

allure-maven plugin will use Maven Central (as for [2.10.0 release](https://github.com/allure-framework/allure-maven/releases/tag/2.10.0)) for Allure Report versions [above 2.8.0 ](https://github.com/allure-framework/allure-maven/blob/2692e522a937c982074a907226d70a271a3b6868/src/main/java/io/qameta/allure/maven/DownloadUtils.java#L30)

**Comment by lewisob-wx** [comment] 2021-03-29 21:49
> @lewisob What issues do you have with Maven builds?
> 
We were getting a 403 for https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-kotlin-android/2.2.0/allure-kotlin-android-2.2.0.pom
Using allure plugin version 2.8.1

**Comment by lewisob** [comment] 2021-03-29 21:50
> @lewisob What issues do you have with Maven builds?
> 
We were getting a 403 for https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-kotlin-android/2.2.0/allure-kotlin-android-2.2.0.pom
Using allure plugin version 2.8.1

**Comment by baev** [comment] 2021-03-30 10:49
@lewisob https://github.com/allure-framework/allure-kotlin/issues/55
 next release of allure-kotlin goes to Maven Central for sure

**Comment by Kev-ASU** [comment] 2021-05-05 21:54
Having same issue. Cannot install, fails everytime. I am following the instructions given on the official site too: https://docs.qameta.io/allure/#_windows
```
Installing 'allure' (2.13.9) [64bit]
The remote server returned an error: (403) Forbidden.
URL https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-commandline/2.13.9/allure-commandline-2.13.9.zip is not valid
```

**Comment by stevegraykcf** [comment] 2021-05-06 18:54
Same here trying to figure out some kind of work around

scoop install allure
Installing 'allure' (2.13.9) [64bit]
The remote server returned an error: (403) Forbidden.
URL https://dl.bintray.com/qameta/maven/io/qameta/allure/allure-commandline/2.13.9/allure-commandline-2.13.9.zip is not valid

**Comment by stevegraykcf** [comment] 2021-05-06 19:12
As far as windows and powershell goes, I was able to download and install it using this script

`Invoke-WebRequest -uri "https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.9/allure-commandline-2.13.9.zip" -Method "GET"  -Outfile allure.zip
Expand-Archive -LiteralPath 'allure.zip' -DestinationPath .\allure-commandline
$env:Path += ";.\allure-commandline\allure-2.13.9\bin" `

the releases are all here
https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/

Then its just a matter of downloading the right zip file, and then adding the extracted bin directory to your path

**Closed** 2021-09-14 13:42 UTC
Labels: type:invalid
