### ISSUE TITLE
Trend chart should shows jenkins build ids

### ISSUE THREAD

**Issue by netmajor** [allure-framework/allure2#362] opened 2017-05-29 08:41 UTC
In my project i am used allure1 from begginig and start using allure2 since about 2 weeks.
In trend chart allure2 shows ids since first using of allure2 from #0 id, but it should shows id of jenkins build. I have attached examples...
![trend](https://cloud.githubusercontent.com/assets/649986/26542697/48fec01a-445b-11e7-9662-7f747c2749fa.PNG)
![history](https://cloud.githubusercontent.com/assets/649986/26542703/4f9b613a-445b-11e7-9be0-8c7a1ee31e91.PNG)

**Comment by baev** [comment] 2017-05-29 11:21
yep, the problem is that trend graph currently not attached to builds, will be fixed during https://github.com/allure-framework/allure2/issues/351

**Closed** 2017-06-19 13:42 UTC
Labels: review
