### ISSUE TITLE
If user click on a test items, other previously opened test packages also got expanded.

### ISSUE THREAD

**Issue by gavrilfb** [allure-framework/allure2#575] opened 2017-08-22 09:48 UTC
#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
If user click on a test items, other previously opened test packages also got expanded.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Open a test item on package A
2. Collapse package A
3. Open test item on package B
![2017-08-22_16-47-06](https://user-images.githubusercontent.com/29943195/29559572-a94a2bd0-8759-11e7-8aed-ba50e74dda6f.gif)

#### What is the expected behavior?
Package A stay collapsed. Only package B got expanded.

#### Please tell us about your environment:

| Allure version | 2.3.4 |
| ---- | ---- | 
| Test framework | testng@6.11 |
| Allure adaptor | allure-testng@2.0-BETA16 |
| Generate report using | allure-jenkins-plugin@2.22 |

**Comment by TpSr52** [comment] 2017-10-11 15:14
@baev It seems like it happens because of this line: "this.$('.node__expanded').parents('.node').toggleClass('node__expanded', true);" (Line 115 in TreeView.js)

What this line of code supposed to do?

**Comment by baranoff-ivan** [comment] 2017-11-16 10:20
It may seem insignificant, but it is very annoying.

**Comment by EltonZhong** [comment] 2018-10-29 14:22
It's also reproduced on suites

**Comment by EltonZhong** [comment] 2018-10-30 02:01
It's been a year. Why is this issue still open? Has it been fixed in any version?

**Comment by vkuchere** [comment] 2018-11-29 11:16
This bug still reproduced in 2.8,1v pls fix it..

**Comment by vkuchere** [comment] 2020-03-05 09:25
Hello everyone, if anyone is interested, I have a fix with a bug https://github.com/allure-framework/allure2/issues/575 uploaded to https://dropmefiles.com.ua/a5V2

**Closed** 2020-07-28 15:14 UTC
Labels: theme:ui, type:bug, work:selected for dev
