### ISSUE TITLE
403 forbidden allure-2.4.1

### ISSUE THREAD

**Issue by zpavlig** [allure-framework/allure2#875] opened 2018-12-26 06:43 UTC
Hello

Can't install allure: Server returned HTTP response code: 403 for URL: https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.4.1/allure-2.4.1.zip

thx.

**Comment by baev** [comment] 2019-01-10 15:34
Duplicate of #832

PS 

@zpavlig upgrade to the latest version of allure (2.9.0 at the moment)

@sqli0189 we will update brew formula to use Maven Central instead of Bintray today

**Closed by baev** 2019-01-10 15:34 UTC
