### ISSUE TITLE
DevOps Plugin - Unknown Test Runner

### ISSUE THREAD

**Issue by digikiwam** [allure-framework/allure2#880] opened 2018-12-18 20:33 UTC
Running Plugin in Azure DevOps generated the following error.

Unable to process command '##vso[results.publish type=Allure;mergeResults=true;publishRunAttachments=true;resultFiles=D:\a\1\s\allure-report\20181218.4;]' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)

Unknown Test Runner.

I have the test results pointing to the solutions folder.

$(Build.SourcesDirectory)\MyTest\MyTest\bin\$(BuildConfiguration)\)allure-results

Only solution out there is a workaround of using the command line task to gen the report.
There is no documentation in the wiki for DevOps or VSTS Plugin (only one missing).

Suggestions?

**Comment by baev** [comment] 2019-01-14 15:35
@digikiwam am I right that you are having troubles with https://marketplace.visualstudio.com/items?itemName=Molecula.allure-test-reports ?

**Comment by digikiwam** [comment] 2019-01-14 19:03
Yes,

I have a build in VSTS that uses the Allure VSTS report generator add in.

When I run the build,  the Generate Allure Report task fails.
I have tried numerous paths to the results location – no luck.
I have some success using a command line, however results are still not generated.

[cid:image001.png@01D4AC09.6D2DD3B0]

I searched for other users that have this issue, the only post I could find was this…
https://stackoverflow.com/questions/48691288/allure-plugin-for-vsts-returns-error-unknown-test-runner

and I have tried both the suggestions workaround, no luck.

I have this repo on my external VSTS and can share if you want to take a look (there is no proprietary code in this repo).

Thanks

**Comment by stambecg** [comment] 2020-02-12 10:06
Hi Team,

Allure Test Reports plugin is not working on Azure, i am getting below error could you please look into it.

I have checked C:\agent\_work\2\s\target\allure-results contains multiple files


2020-02-12T09:42:21.9156093Z ##[section]Starting: Generate Allure Report
2020-02-12T09:42:22.0589528Z ==============================================================================
2020-02-12T09:42:22.0589617Z Task : Generate Allure Report
2020-02-12T09:42:22.0589645Z Description : Generates Allure report based on the test results
2020-02-12T09:42:22.0589673Z Version : 1.0.0
2020-02-12T09:42:22.0589697Z Author : Molecula
2020-02-12T09:42:22.0589727Z Help : [More Information](https://github.com/allure-framework/allure-core/wiki)
2020-02-12T09:42:22.0589752Z ==============================================================================
2020-02-12T09:42:22.9191463Z [command]C:\Program Files\nodejs\node.exe C:\agent\_work\_tasks\AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacfb\1.0.0\node_modules\allure-commandline\bin\allure generate --output C:\agent\_work\2\s\allure-report\20200212.10 C:\agent\_work\2\s\target\allure-results
2020-02-12T09:42:26.9963352Z Command aborted due to exception {}.

2020-02-12T09:42:26.9963671Z Exception in thread "main" ru.yandex.qatools.allure.data.ReportGenerationException: Could not find any allure results

2020-02-12T09:42:26.9963753Z org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)

2020-02-12T09:42:26.9963833Z at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:58)
2020-02-12T09:42:26.9963900Z at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
2020-02-12T09:42:26.9964290Z at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
2020-02-12T09:42:26.9964350Z at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
2020-02-12T09:42:26.9964634Z at ru.yandex.qato

**Comment by VStepulo** [comment] 2020-03-02 15:30
Has the same error as @stambecg 
2020-03-02T15:11:27.3512712Z ##[section]Starting: Generate Allure Report
2020-03-02T15:11:27.3629874Z ==============================================================================
2020-03-02T15:11:27.3630373Z Task         : Generate Allure Report
2020-03-02T15:11:27.3630702Z Description  : Generates Allure report based on the test results
2020-03-02T15:11:27.3630987Z Version      : 1.0.0
2020-03-02T15:11:27.3631230Z Author       : Molecula
2020-03-02T15:11:27.3631598Z Help         : [More Information](https://github.com/allure-framework/allure-core/wiki)
2020-03-02T15:11:27.3632039Z ==============================================================================
2020-03-02T15:11:27.6307062Z [command]C:\Program Files\nodejs\node.exe D:\a\_tasks\AllureGenerate_5c975f9d-1c3a-469f-b7c2-8907bf3eacfb\1.0.0\node_modules\allure-commandline\bin\allure generate --output D:\a\1\s\allure-report\20200302.11 D:\a\1\s\Interdan.UI.Automation.Tests\bin\Debug\netcoreapp3.1\allure-results
2020-03-02T15:11:38.1776411Z Exception in thread "main" ru.yandex.qatools.allure.data.ReportGenerationException: Could not find any allure results
2020-03-02T15:11:38.1777217Z Command aborted due to exception {}.
2020-03-02T15:11:38.1778001Z 	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:58)
2020-03-02T15:11:38.1778542Z org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
2020-03-02T15:11:38.1779230Z 	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
2020-03-02T15:11:38.1779716Z 	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
2020-03-02T15:11:38.1780329Z 	at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
2020-03-02T15:11:38.1780844Z 	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
2020-03-02T15:11:38.1781593Z 	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
2020-03-02T15:11:38.1782186Z 	at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
2020-03-02T15:11:38.1782808Z 	at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
2020-03-02T15:11:38.1783356Z 	at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)
2020-03-02T15:11:38.1784577Z org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
2020-03-02T15:11:38.1785214Z 	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)

The reports are present in D:\a\1\s\Interdan.UI.Automation.Tests\bin\Debug\netcoreapp3.1\allure-results:

    Directory: D:\a\1\s\Interdan.UI.Automation.Tests\bin\Debug\netcoreapp3.1\allure-results


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----         3/2/2020   3:11 PM            851 0-1004_2d78f52b14f54d4fb40fd0f0502e7edf-0-1003-run1-container-12971690
                                                 -6507-4b0e-89ec-8d170a9cef73-container.json                           
-a----         3/2/2020   3:11 PM          18002 0-1004_2d78f52b14f54d4fb40fd0f0502e7edf-0-1003-test-run1-77d9d85f-942d
                                                 -4859-8215-83e20ac6a376-result.json                                   
-a----         3/2/2020   3:11 PM         212024 afeea907fc0d4e998a6fe58d5d517c33-attachment                           
-a----         3/2/2020   3:10 PM            675 categories.json                                                       
-a----         3/2/2020   3:11 PM            117 environment.properties

**Comment by Garynychxxx** [comment] 2020-03-04 15:40
Do you have any updates by this issue?

**Comment by fescobar** [comment] 2020-03-04 16:59
@Garynychxxx seems to be nobody is maintaining this plugin.

https://github.com/allure-framework/allure2/issues/919

**Comment by ElkRom** [comment] 2021-12-30 08:49
Will someone fix this issue?

**Comment by alexzavg** [comment] 2022-08-15 21:18
having the same error with playwright allure in azure

**Comment by uLucasFraga** [comment] 2022-12-29 11:21
> having the same error with playwright allure in azure

The same here!
Any update?

Thanks!

**Comment by ManuSharma22796** [comment] 2023-08-17 19:34
Same issue !
Any update or workaround, i'm using tech maven+java+playwright?

Thanks

**Comment by baev** [comment] 2024-01-08 18:18
Duplicate of #1140

**Closed by baev** 2024-01-08 18:18 UTC
Labels: waiting for feedback

**Comment by baev** [comment] 2024-02-01 12:45
Official Allure extension for Azure Pipelines are now available https://marketplace.visualstudio.com/items?itemName=qameta.allure-azure-pipelines

History isn't yet supported, but we'll get there! Please submit feedback to our [discussions](https://github.com/orgs/allure-framework/discussions)
