### ISSUE TITLE
latest version beta16 causes a crash

### ISSUE THREAD

**Issue by tnimni** [allure-framework/allure2#565] opened 2017-08-17 19:32 UTC
I created an empty project, and copy pasted the pom from allure guide

than I wrote a single test, which only write something to System.out

and i get the following

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project allure2-test: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/tsachinimni/source/allure2test/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] Test mechanism :: null
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Test mechanism :: null
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:665)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:243)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1077)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:907)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:785)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by baev** [comment] 2017-08-18 10:20
That seems like surefire issue. Is something wrong with Allure? 

Surefire issues with same error message:
https://issues.apache.org/jira/browse/SUREFIRE-1305 https://issues.apache.org/jira/browse/SUREFIRE-707

**Comment by tnimni** [comment] 2017-08-18 13:30
@baev I reverted to allure1 and all works fine, when using allure1 it crahses
I was unable to figure out what's the problem with surefire, I investigated for 2 days
I think it's allure issue

**Comment by baev** [comment] 2017-08-18 13:33
In that case could you please provide minimal demo to reproduce the problem?

**Comment by tnimni** [comment] 2017-08-19 19:13
@baev I will create a git repo and link it here in the morning with all additional details

**Comment by tnimni** [comment] 2017-08-20 11:31
@baev I uploaded it to https://github.com/tnimni/allure2
please note that I also included the target directory just incase your computer complies diffrently

I'm using OSX 10.12.6
allure 2.0-BETA16
aspectj 1.8.10
surefire 2.20
junit 4.12
java 1.8.0_121

Regards

**Comment by baev** [comment] 2017-08-20 12:51
The problem is that you are using default package for test. Already fixed in https://github.com/allure-framework/allure-java/pull/134 , will be available in 2.0-BETA17

**Closed by baev** 2017-08-20 12:51 UTC
Labels: type:bug, work:backlog

**Comment by tnimni** [comment] 2017-08-20 19:52
@baev thanks :)
