### ISSUE TITLE
AllureGenerate report ##[error]Not found node: null

### ISSUE THREAD

**Issue by ghost** [allure-framework/allure2#1893] opened 2023-01-16 17:37 UTC
I have to prepare Allure report from existing results in Azure pipeline. On task run it reports **##[error]Not found node: null**
If I manually create report using "gradle allureReport" it  is being done successfully.

**Comment by baev** [comment] 2024-01-10 16:49
Duplicate of #1140

**Closed by baev** 2024-01-10 16:49 UTC

**Comment by baev** [comment] 2024-02-01 12:45
Official Allure extension for Azure Pipelines are now available https://marketplace.visualstudio.com/items?itemName=qameta.allure-azure-pipelines

History isn't yet supported, but we'll get there! Please submit feedback to our [discussions](https://github.com/orgs/allure-framework/discussions)
