### ISSUE TITLE
Feature request. Allure TestsOps doesn’t support Basic Authorization header witch comes from Nginx to Jenkins

### ISSUE THREAD

**Issue by r4m-sergiys** [allure-framework/allure2#2104] opened 2023-09-06 21:19 UTC
I have the Jenkins environment which configured with docker-compose and nginx. In the nginx config file I configured basic authorization header. 
So, when I want to configure Jenkins Integration in the TestOps, I’m getting 401 status code.

**Expected result:**
It is a possible to setup Jenkins Integration in the TestOps with using Basic Authorization header which comes from nginx to Jenkins.

_Originally posted by @r4m-sergiys in https://github.com/allure-framework/allure2/discussions/2101_

**Comment by baev** [comment] 2023-09-07 12:00
Duplicate of https://github.com/orgs/allure-framework/discussions/2101

**Closed by baev** 2023-09-07 12:00 UTC

**Comment by r4m-sergiys** [comment] 2023-09-07 17:41
Hi, @baev. will this feature be implemented in the near future?
